# services:
#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "5173:5173"
#     tty: true
#     stdin_open: true
#     volumes:
#       - ./frontend:/app

#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "4000:4000"
#     environment:
#       DB_HOST: db
#       DB_USER: admin
#       DB_PASSWORD: secret
#       DB_NAME: fertilitech
#       DB_PORT: 5432
#     depends_on:
#       - db

#   db:
#     image: postgres:16
#     restart: always
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: fertilitech
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   pgadmin:
#     image: dpage/pgadmin4:7.6
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@fertilitech.com
#       PGADMIN_DEFAULT_PASSWORD: admin123
#       CSRF_ENABLED: 'False'
#     ports:
#       - "5050:80"
#     depends_on:
#       - db
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin

# volumes:
#   pgdata:
#   pgadmin-data:
